### test connection

GET http://localhost:3000/api/users/

### user find

GET http://localhost:3000/api/users/?id=6683e0e7f10f6449f222218e

### user list

GET http://localhost:3000/api/users/list

### register users

POST http://localhost:3000/api/users/register
Content-Type: application/json
Accept: application/json

{
    "name" : "mgmg",
    "email" : "alice@gmail.com",
    "password" : "12345",
    "role" : "user",
    "image" : "profie image"
}

### login user

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
   "email": "mg@gmail.com",
   "password" :"12345"
}

### verify

GET http://localhost:3000/api/users/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ODRjOGRiZmZlYmU2YTJkZmRiMjNhNSIsIm5hbWUiOiJtZ21nIiwiZW1haWwiOiJtZ0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQxUTVzY3IvdC9UaGxUdTFmQnBybmRlWW9tbEVIOGZjNnBnVFF2VWxYR3FLLkowN2Z2Wi4vTyIsImltYWdlIjoicHJvZmlsZSBpbWFnZSIsImJvb2ttYXJrIjpbXSwicm9sZSI6InVzZXIiLCJfX3YiOjB9LCJpYXQiOjE3MjAwMTgwMzMsImV4cCI6MTcyMDEwNDQzM30.xgHc2ihhlyk_3kdVl4nIpyKc5ju80l6wAvifx1VCoR4

### update

PUT http://localhost:3000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ODRjOGRiZmZlYmU2YTJkZmRiMjNhNSIsIm5hbWUiOiJtZ21nIiwiZW1haWwiOiJtZ0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQxUTVzY3IvdC9UaGxUdTFmQnBybmRlWW9tbEVIOGZjNnBnVFF2VWxYR3FLLkowN2Z2Wi4vTyIsImltYWdlIjoicHJvZmlsZSBpbWFnZSIsImJvb2ttYXJrIjpbXSwicm9sZSI6InVzZXIiLCJfX3YiOjB9LCJpYXQiOjE3MjAwMTgwMzMsImV4cCI6MTcyMDEwNDQzM30.xgHc2ihhlyk_3kdVl4nIpyKc5ju80l6wAvifx1VCoR4
Content-Type: application/json
Accept: application/json


{
    "name" : "mgmg"
}

### user delete 

DELETE http://localhost:3000/api/users/66854c749b49164f19aabf27
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ODRjOGRiZmZlYmU2YTJkZmRiMjNhNSIsIm5hbWUiOiJtZ21nIiwiZW1haWwiOiJtZ0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQxUTVzY3IvdC9UaGxUdTFmQnBybmRlWW9tbEVIOGZjNnBnVFF2VWxYR3FLLkowN2Z2Wi4vTyIsImltYWdlIjoicHJvZmlsZSBpbWFnZSIsImJvb2ttYXJrIjpbXSwicm9sZSI6InVzZXIiLCJfX3YiOjB9LCJpYXQiOjE3MjAwMTgwMzMsImV4cCI6MTcyMDEwNDQzM30.xgHc2ihhlyk_3kdVl4nIpyKc5ju80l6wAvifx1VCoR4